import React from "react";
import Navigation from "./Nav";
//import ReactDOM from 'react-dom';
import "./dashboard/dashboard.css";
//import Spinner from "./img/Spinner.gif";
import Spinner from "./img/Spinnergrey.gif";
//import Spinner from "./img/Magnify.gif";
import addicon from "./img/add.png";
import { Link, Redirect } from "react-router-dom";
import axios from "axios";

const BASE = "https://stage.mconnecthealth.com";


class Alldepartment extends React.Component {
    constructor(props) {
        super(props);
        const token = localStorage.getItem("token");

        let loggedIn = true;
        if (token == null) {
            loggedIn = false;
        }
        this.state = {
            loggedIn,
            posts: [],
        };
    }

    render() {
        if (localStorage.getItem("token") == null) {
            return <Redirect to="/Dashboard" />;
        }
        return (
            <div className="Appcontainer">
                <Navigation />
                <div className="allfooter">
                    <div className="backarrow">
                        <Link to="/Dashboard">
                            <i className="fas fa-arrow-left"></i>
                        </Link>{" "}
                    </div>
                    <h2>Terms and Condition</h2>
                    <b>PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY</b>
                    <div>
                        <ul>
                            <li>
                                <div>
                                    {/* <img
                                        src={addicon}
                                        alt="Step-1"
                                    /> */}
                                    <p>
                                        INFRINGEMENTS
                                       <p> We respect the intellectual AGREEMENT TO TERMS
                                        These Terms and Conditions constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) and [business entity name] (“we,” “us” or “our”), concerning your access to and use of the [website name.com] website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively, the “Site”). You agree that by accessing the Site, you have read, understood, and agree to be bound by all of these Terms and Conditions Use. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS and CONDITIONS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY.

                                        Supplemental terms and conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms and Conditions at any time and for any reason. We will alert you about any changes by updating the “Last updated” date of these Terms and Conditions and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Terms and Conditions to stay informed of updates. You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised Terms and Conditions by your continued use of the Site after the date such revised Terms are posted.

                                        The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.

                                        These Terms and Conditions were generated by Termly’s Terms and Conditions Generator.

                                        Option 1: The Site is intended for users who are at least 18 years old. Persons under the age of 13 are not permitted to register for the Site.

                                        Option 2: [The Site is intended for users who are at least 13 years of age.] All users who are minors in the jurisdiction in which they reside (generally under the age of 18) must have the permission of, and be directly supervised by, their parent or guardian to use the Site. If you are a minor, you must have your parent or guardian read and agree to these Terms of Use prior to you using the Site.
                                        </p>

                                    </p>
                                </div>
                            </li>
                        </ul>
                    </div>

                    <div style={{ marginBottom: '10px' }}>
                        <ul >
                            <li >
                                <div >
                                    {/* <img
                                        src={addicon}
                                        alt="Step-1"
                                    /> */}
                                    <p>
                                        INTELLECTUAL PROPERTY RIGHTS
                                       <p> Unless otherwise indicated, the Site is our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the “Content”) and the trademarks, service marks, and logos contained therein (the “Marks”) are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws of the United States, foreign jurisdictions, and international conventions. The Content and the Marks are provided on the Site “AS IS” for your information and personal use only. Except as expressly provided in these Terms of Use, no part of the Site and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.

                                        Provided that you are eligible to use the Site, you are granted a limited license to access and use the Site and to download or print a copy of any portion of the Content to which you have properly gained access solely for your personal, non-commercial use. We reserve all rights not expressly granted to you in and to the Site, Content and the Marks.

                                        </p>

                                    </p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div style={{ marginBottom: '10px' }}>
                        <ul >
                            <li >
                                <div >
                                    {/* <img
                                        src={addicon}
                                        alt="Step-1"
                                    /> */}
                                    <p>
                                        USER REPRESENTATIONS
                                       <p> By using the Site, you represent and warrant that: [(1) all registration information you submit will be true, accurate, current, and complete; (2) you will maintain the accuracy of such information and promptly update such registration information as necessary;] (3) you have the legal capacity and you agree to comply with these Terms of Use; [(4) you are not under the age of 13;] (5) not a minor in the jurisdiction in which you reside[, or if a minor, you have received parental permission to use the Site]; (6) you will not access the Site through automated or non-human means, whether through a bot, script or otherwise; (7) you will not use the Site for any illegal or unauthorized purpose; and (8) your use of the Site will not violate any applicable law or regulation.

                                        If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Site (or any portion thereof).

                                        </p>

                                    </p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div style={{ marginBottom: '10px' }}>
                        <ul >
                            <li >
                                <div >
                                    {/* <img
                                        src={addicon}
                                        alt="Step-1"
                                    /> */}
                                    <p>
                                        USER REGISTRATION
                                       <p> You may be required to register with the Site. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.
                                        </p>

                                    </p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div style={{ marginBottom: '10px' }}>
                        <ul >
                            <li >
                                <div >
                                    {/* <img
                                        src={addicon}
                                        alt="Step-1"
                                    /> */}
                                    <p>
                                        PROHIBITED ACTIVITIES
                                       <p> You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.

                                        As a user of the Site, you agree not to:

                                        1.	systematically retrieve data or other content from the Site to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.
                                        2.	make any unauthorized use of the Site, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.
                                        3.	use a buying agent or purchasing agent to make purchases on the Site.
                                        4.	use the Site to advertise or offer to sell goods and services.
                                        5.	circumvent, disable, or otherwise interfere with security-related features of the Site, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Site and/or the Content contained therein.
                                        6.	engage in unauthorized framing of or linking to the Site.
                                        7.	trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords;
                                        8.	make improper use of our support services or submit false reports of abuse or misconduct.
                                        9.	engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.
                                        10.	interfere with, disrupt, or create an undue burden on the Site or the networks or services connected to the Site.
                                        11.	attempt to impersonate another user or person or use the username of another user.
                                        12.	sell or otherwise transfer your profile.
                                        13.	use any information obtained from the Site in order to harass, abuse, or harm another person.
                                        14.	use the Site as part of any effort to compete with us or otherwise use the Site and/or the Content for any revenue-generating endeavor or commercial enterprise.
                                        15.	decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Site.
                                        16.	attempt to bypass any measures of the Site designed to prevent or restrict access to the Site, or any portion of the Site.
                                        17.	harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Site to you.
                                        18.	delete the copyright or other proprietary rights notice from any Content.
                                        19.	copy or adapt the Site’s software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.
                                        20.	upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Site or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Site.
                                        21.	upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats (“gifs”), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pcms”).
                                        22.	except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Site, or using or launching any unauthorized script or other software.
                                        23.	disparage, tarnish, or otherwise harm, in our opinion, us and/or the Site.
                                        24.	use the Site in a manner inconsistent with any applicable laws or regulations.

                                        </p>

                                    </p>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        );

    }
}
export default Alldepartment;
